### ISSUE TITLE
workflow file issue

### ISSUE THREAD

**Issue by sajualways** [tls-attacker/TLS-Attacker#129]
06:59:27 [main] ERROR: TlsClient - Encountered an uncaught Exception aborting. See debug for more info.
javax.xml.bind.UnmarshalException
 - with linked exception:
[org.xml.sax.SAXParseException; lineNumber: 38; columnNumber: 40; cvc-complex-type.2.4.a: Invalid content was found starting with element 'byteArrayExplicitValueModification'. One of '{BigIntegerXorModification, BigIntegerSubtractModification, BigIntegerShiftRightModification, BigIntegerShiftLeftModification, BigIntegerExplicitValueModification, BigIntegerAddModification, BigIntegerInteractiveModification, BigIntegerMultiplyModification, BooleanToggleModification, BooleanExplicitValueModification, ByteArrayXorModification, ByteArrayShuffleModification, ByteArrayPayloadModification, ByteArrayInsertModification, ByteArrayExplicitValueModification, ByteArrayDuplicateModification, ByteArrayDeleteModification, IntegerXorModification, IntegerSubtractModification, IntegerShiftRightModification, IntegerShiftLeftModification, IntegerExplicitValueModification, IntegerAddModification, LongXorModification, LongSubtractModification, LongExplicitValueModification, LongAddModification, ByteXorModification, ByteSubtractModification, ByteAddModification, ByteExplicitValueModification, StringExplicitValueModification, assertEquals, originalValue}' is expected.]
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.handleStreamException(UnmarshallerImpl.java:453)
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:387)
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:356)
        at de.rub.nds.tlsattacker.core.workflow.WorkflowTraceSerializer.secureRead(WorkflowTraceSerializer.java:229)
        at de.rub.nds.tlsattacker.client.main.TlsClient.main(TlsClient.java:57)
Caused by: org.xml.sax.SAXParseException; lineNumber: 38; columnNumber: 40; cvc-complex-type.2.4.a: Invalid content was found starting with element 'byteArrayExplicitValueModification'. One of '{BigIntegerXorModification, BigIntegerSubtractModification, BigIntegerShiftRightModification, BigIntegerShiftLeftModification, BigIntegerExplicitValueModification, BigIntegerAddModification, BigIntegerInteractiveModification, BigIntegerMultiplyModification, BooleanToggleModification, BooleanExplicitValueModification, ByteArrayXorModification, ByteArrayShuffleModification, ByteArrayPayloadModification, ByteArrayInsertModification, ByteArrayExplicitValueModification, ByteArrayDuplicateModification, ByteArrayDeleteModification, IntegerXorModification, IntegerSubtractModification, IntegerShiftRightModification, IntegerShiftLeftModification, IntegerExplicitValueModification, IntegerAddModification, LongXorModification, LongSubtractModification, LongExplicitValueModification, LongAddModification, ByteXorModification, ByteSubtractModification, ByteAddModification, ByteExplicitValueModification, StringExplicitValueModification, assertEquals, originalValue}' is expected.
        at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
        at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:135)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
        at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(XMLSchemaValidator.java:511)
        at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.reportSchemaError(XMLSchemaValidator.java:3587)
        at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:1971)
        at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:829)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorHandlerImpl.startElement(ValidatorHandlerImpl.java:570)
        at com.sun.xml.bind.v2.runtime.unmarshaller.ValidatingUnmarshaller.startElement(ValidatingUnmarshaller.java:71)
        at com.sun.xml.bind.v2.runtime.unmarshaller.InterningXmlVisitor.startElement(InterningXmlVisitor.java:45)
        at com.sun.xml.bind.v2.runtime.unmarshaller.StAXStreamConnector.handleStartElement(StAXStreamConnector.java:216)
        at com.sun.xml.bind.v2.runtime.unmarshaller.StAXStreamConnector.bridge(StAXStreamConnector.java:150)
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:385)
        ... 3 more

**Comment by sajualways** [comment]
I am getting exception for this line
<byteArrayExplicitValueModification>
                                <explicitValue>
                        47 45 54 20 2f 20 48 54 54 50 2f 31 2e 31 0d 0a
48 6f 73 74 3a 20 31 30 2e 31 30 32 2e 31 31 33
2e 32 33 0d 0a 55 73 65 72 2d 41 67 65 6e 74 3a
20 63 75 72 6c 2f 37 2e 36 31 2e 31 0d 0a 41 63
63 65 70 74 3a 20 2a 2f 2a 0d 0a 0d 0a
                                </explicitValue>
                        </byteArrayExplicitValueModification>

**Comment by ic0ns** [comment]
I think the issue is that we changed the capiatlisation in newer versions of TLS-Attacker. Try **B**yteArrayExplicit...
