### ISSUE TITLE
Got this error while sending  client certificate message  with chain of certificates in one file

### ISSUE THREAD

**Issue by sajualways** [tls-attacker/TLS-Attacker#168]
10:20:22 [main] WARN : Delegate - Could not read certificate
java.security.cert.CertificateParsingException: signed overrun, bytes = 1820
        at java.base/sun.security.x509.X509CertImpl.parse(X509CertImpl.java:1826)
        at java.base/sun.security.x509.X509CertImpl.<init>(X509CertImpl.java:194)
        at java.base/sun.security.provider.X509Factory.parseX509orPKCS7Cert(X509Factory.java:476)
        at java.base/sun.security.provider.X509Factory.engineGenerateCertificates(X509Factory.java:361)
        at java.base/java.security.cert.CertificateFactory.generateCertificates(CertificateFactory.java:478)
        at de.rub.nds.tlsattacker.core.certificate.PemUtil.readCertificate(PemUtil.java:122)
        at de.rub.nds.tlsattacker.core.certificate.PemUtil.readCertificate(PemUtil.java:134)
        at de.rub.nds.tlsattacker.core.config.delegate.CertificateDelegate.applyDelegate(CertificateDelegate.java:122)
        at de.rub.nds.tlsattacker.core.config.TLSDelegateConfig.createConfig(TLSDelegateConfig.java:67)
        at de.rub.nds.tlsattacker.core.config.TLSDelegateConfig.createConfig(TLSDelegateConfig.java:85)
        at de.rub.nds.tlsattacker.client.config.ClientCommandConfig.createConfig(ClientCommandConfig.java:111)
        at de.rub.nds.tlsattacker.client.main.TlsClient.main(TlsClient.java:52)

**Comment by sajualways** [comment]
Is it possible to send client certificate chain using java -jar TLS-Client.jar -connect host:port -cert  <cert_chain.pem> -key <key.pem>

**Comment by ic0ns** [comment]
Which version are you on?

**Comment by ic0ns** [comment]
Anyways, I think this is not possible through the commandline interface. Anything X.509 is a bit of a weakness of TLS-Attacker in the current version. Our next version has reworked this. In the meantime, you would either need to set the certificate in the workflow trace, manually set the certificates in the config or change the code of TLS-Attacker.

**Comment by sajualways** [comment]
I was looking for -key kind of option 
like for example " -cert "

**Comment by sajualways** [comment]
> Which version are you on?

I am using latest git update

**Comment by sajualways** [comment]
> Anyways, I think this is not possible through the commandline interface. Anything X.509 is a bit of a weakness of TLS-Attacker in the current version. Our next version has reworked this. In the meantime, you would either need to set the certificate in the workflow trace, manually set the certificates in the config or change the code of TLS-Attacker.

Can we have a option -cert_chain <> option ?

**Comment by ic0ns** [comment]
Ok so what you can do in the new version is just provide a pem file with one or more certificates. The next release will document this better. Issue was actually addressed a while ago but was not closed.
