### ISSUE TITLE
" Tag invalid Exception" found when we receive Hello Retry Request during TLSv1.3 Handshake from Server side

### ISSUE THREAD

**Issue by sajualways** [tls-attacker/TLS-Attacker#83]
03:31:45 [main] WARN : RecordAEADCipher - Tag invalid
de.rub.nds.tlsattacker.core.exceptions.CryptoException: Could not decrypt data
	at de.rub.nds.tlsattacker.core.crypto.cipher.JavaCipher.decrypt(JavaCipher.java:193)
	at de.rub.nds.tlsattacker.core.record.cipher.RecordAEADCipher.decrypt(RecordAEADCipher.java:224)
	at de.rub.nds.tlsattacker.core.record.crypto.RecordDecryptor.decrypt(RecordDecryptor.java:67)
	at de.rub.nds.tlsattacker.core.record.crypto.Decryptor.decrypt(Decryptor.java:32)
	at de.rub.nds.tlsattacker.core.record.layer.TlsRecordLayer.decryptAndDecompressRecord(TlsRecordLayer.java:180)
	at de.rub.nds.tlsattacker.core.workflow.action.executor.RecordGroup.decryptRecords(RecordGroup.java:112)
	at de.rub.nds.tlsattacker.core.workflow.action.executor.ReceiveMessageHelper.processRecordGroup(ReceiveMessageHelper.java:141)
	at de.rub.nds.tlsattacker.core.workflow.action.executor.ReceiveMessageHelper.handleReceivedBytes(ReceiveMessageHelper.java:131)
	at de.rub.nds.tlsattacker.core.workflow.action.executor.ReceiveMessageHelper.receiveMessages(ReceiveMessageHelper.java:77)
	at de.rub.nds.tlsattacker.core.workflow.action.ReceiveAction.execute(ReceiveAction.java:149)
	at de.rub.nds.tlsattacker.core.workflow.DefaultWorkflowExecutor.executeWorkflow(DefaultWorkflowExecutor.java:76)
	at de.rub.nds.tlsattacker.client.main.TlsClient.startTlsClient(TlsClient.java:68)
	at de.rub.nds.tlsattacker.client.main.TlsClient.main(TlsClient.java:51)
Caused by: javax.crypto.AEADBadTagException: Tag mismatch!
	at com.sun.crypto.provider.GaloisCounterMode.decryptFinal(GaloisCounterMode.java:592)
	at com.sun.crypto.provider.CipherCore.finalNoPadding(CipherCore.java:1116)
	at com.sun.crypto.provider.CipherCore.fillOutputBuffer(CipherCore.java:1053)
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:853)
	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
	at javax.crypto.Cipher.doFinal(Cipher.java:2168)
	at de.rub.nds.tlsattacker.core.crypto.cipher.JavaCipher.decrypt(JavaCipher.java:185)
	... 12 more

**Comment by sajualways** [comment]
To be more clear this was my flow->As per RFC i need to send the second Client hello with updated Key share extension in 2nd Client hello

03:36:08 [main] INFO : SendAction - Sending messages (client): CLIENT_HELLO, 
03:36:08 [main] INFO : ReceiveAction - Received Messages (client): SERVER_HELLO, CHANGE_CIPHER_SPEC, 
03:36:08 [main] INFO : SendAction - Sending messages (client): CLIENT_HELLO, 
03:36:08 [main] WARN : RecordAEADCipher - Tag invalid
de.rub.nds.tlsattacker.core.exceptions.CryptoException: Could not decrypt data

**Comment by ic0ns** [comment]
This is very hard to debug with this information - can you provide more?
